---
- name: Install apache server
  hosts: all
  remote_user: ansible_user
  become: yes
  gather_facts: no
  tasks:
    - name: Install httpd 
      yum:
        name: httpd
        state: present

    - name: Start httpd 
      service:
        name: httpd
        state: started